### ISSUE TITLE
Could you also add support for the llvm Disasm API

### ISSUE THREAD

**Issue by blacktop** [tinygo-org/go-llvm#16]
This is a great project!

Would it be possible to add support for the LLVM MC (Machine Code) library as well?

https://raywang.tech/2017/12/04/Using-the-LLVM-MC-Disassembly-API/#mcdisassembly

Also this might be a dumb question, but I see you using come Cpp files, does that mean you can link against the C++ API as well?

If so would you be able to link against the C++ version of the MC lib?  That would allow for doing all kinds of interesting static code analysis in Go ❤️

**Comment by aykevl** [comment]
While I have some local patches in this repository (for TinyGo), I think you're best off submitting patches to LLVM directly (from which this code has been derived). From time to time, we incorporate changes from LLVM to this repository.

https://llvm.org/docs/Contributing.html

**Comment by blacktop** [comment]
Will do, thanks!
