### ISSUE TITLE
how can I "go get" this module?

### ISSUE THREAD

**Issue by kamkow1** [tinygo-org/go-llvm#36]
hello,
I'm trying to run a command specified in the README.
```
go get github.com/tinygo-org/go-llvm
```
it gives the following error:
```
go: github.com/tinygo-org/go-llvm@v0.0.0-20220626113704-45f1e2dbf887: parsing go.mod:
	module declares its path as: tinygo.org/x/go-llvm
	        but was required as: github.com/tinygo-org/go-llvm
```
how can I download this module when the github url and module name are different?

**Comment by aykevl** [comment]
Thank you! I have updated the README, the given command was incorrect.
