### ISSUE TITLE
Support LLVMCreateTypeAttribute

### ISSUE THREAD

**Issue by ryan-berger** [tinygo-org/go-llvm#39]
Hello, and thank you for your project! I wrote a compiler in Go for a compiler course, and this project has made converting the compiler over to an LLVM backend super easy.

As I was working on calling some external C code that uses structs, I was trying to use the `byval` attribute, and noticed that `Verify` was crashing with a null pointer exception. As of r362128, `byval` can optionally accept a type, and [LLVMCreateEnumAttribute returns the attribute with a null type](https://llvm.org/doxygen/IR_2Core_8cpp_source.html#l00146) causing a null pointer access when `Verify` is checking the module.

The solution here is to use [LLVMCreateTypeAttribute](https://llvm.org/doxygen/IR_2Core_8cpp_source.html#l00176) which allows you to pass in the attribute kind and type.

I'll try to get a PR for this, but if you feel free if you beat me to it.

**Comment by ryan-berger** [comment]
Fixed in #40

**Comment by aykevl** [comment]
> I wrote a compiler in Go for a compiler course, and this project has made converting the compiler over to an LLVM backend super easy.

Cool! I'm glad it's been useful.

**Comment by aykevl** [comment]
Closing, this has been implemented.
