### ISSUE TITLE
LLVM Intrinsic Support

### ISSUE THREAD

**Issue by alperenunal** [tinygo-org/go-llvm#42]
Hey, is there any reason for you to not to include LLVM's intrinsic functions like `LLVMLookupIntrinsicID`, `LLVMGetIntrinsicDeclaration`? They provide easy way to handle intrinsic functions, especially for overloaded ones.

**Comment by aykevl** [comment]
No particular reason, but you can already create LLVM intrinsics by declaring a function. If you prefer special support for this, feel free to make a pull request.

**Comment by alperenunal** [comment]
#43
