### ISSUE TITLE
TinyGo - Go 

### ISSUE THREAD

**Issue by ShalokShalom** [tinygo-org/go-llvm#44]
Does this binding work for all of Go?

Its hosted by the TinyGo project, and the readme does say nothing about the scope. 

Maybe resolve this by a commit to the readme.

**Comment by aykevl** [comment]
It _only_ works in regular Go. It's a regular Go package, so I'm not sure it needs mentioning? Most other packages in the repo also work with regular Go (or at least they should) - like the bluetooth package.

**Comment by ShalokShalom** [comment]
I had no idea and considering there is a second person hitting this repo where this is the case, I guess mentioning it doesnt harm
